config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "home/index"

  # Garbage stuff used as a test playground
  get "test_area/index"
  get "test_area/experience", to: "test_area#experience"
  get "test_area/:type", to: "test_area#show"

  get "experiences", to: "experience#index"
  get "experiences/:tag", to: "experience#show", as: :experience

  # Admin routes
  post "cache/refresh"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController
  protect_from_forgery with: :null_session

  http_basic_authenticate_with name: ENV["CACHE_REFRESH_USER"], password: ENV["CACHE_REFRESH_PASSWORD"], only: :refresh

  def refresh
    Rails.logger.info("Performing cache refresh")

    # Use a thread pool to fetch data faster (heavily IO bound operations)
    pool = Concurrent::FixedThreadPool.new(12)
    futures = Map::Types::ALL.map do |type|
      Concurrent::Future.execute(executor: pool) do
        { type: type, result: Clients::GooglePlaces.instance.get_places_by_type(type) }
      end
    end
    futures.each(&:wait)

    # Coelesce the responses into a hash that can be written to cache in one request
    cache_data =futures.map(&:value).each_with_object({}) do |response, object|
      object[cache_key(response[:type])] = response[:result]
    end
    Rails.cache.write_multi(cache_data, expires_in: 1.week)

    render json: { status: "ok" }
  end

  private

    def cache_key(type)
      "google_api:places_nearby:type:#{type}"
    end
end

app/controllers/experience_controller.rb
class ExperienceController < ApplicationController
  def index
    @options = PLACES_CONFIG["tags"]
  end

  def show
    # TODO: 404 on bad tag
    tag = params[:tag]
    cache_keys = Map::Types::ALL.map { |type| cache_key(type) }
    places_by_type = Rails.cache.fetch_multi(*cache_keys, expires_in: 1.week) do |key|
      type = cache_key(key)
      Rails.logger.info("Cache miss for type: #{type}")
      Clients::GooglePlaces.instance.get_places_by_type(type)
    end
    places_by_type.transform_values! do |place_data|
      places = place_data[:results].map do |business_data|
        Map::Place.new(business_data)
      end
      places
    end
    @places = places_by_type.values.flatten.uniq { |place| place.google_place_id }

    Map::Place.sanitize_list!(@places)

    @places = Map::Place.only_with_tag(@places, tag)
  end

  private

    def cache_key(type)
      "google_api:places_nearby:type:#{type}"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    cache_keys = Map::Types::ALL.map { |type| cache_key(type) }
    @places_by_type = Rails.cache.fetch_multi(*cache_keys, expires_in: 1.week) do |key|
      type = cache_key_to_type(key)
      Rails.logger.info("Cache miss for type: #{type}")
      Clients::GooglePlaces.instance.get_places_by_type(type)
    end
    @places_by_type.transform_keys! { |key| cache_key_to_type(key) }
    @places_by_type.transform_values! do |place_data|
      places = place_data[:results].map do |business_data|
        Map::Place.new(business_data)
      end
      Map::Place.sanitize_list!(places)
      places
    end
  end

  private

    def cache_key(type)
      "google_api:places_nearby:type:#{type}"
    end

    def cache_key_to_type(key)
      key.split(":").last
    end
end

app/controllers/test_area_controller.rb
# A place to play around on localhost development, to quickly try things out
class TestAreaController < ApplicationController
  def index
    # @places = PLACE_TYPES.each_with_object({}) do |type, result|
    #   result[type.to_sym] = Clients::GooglePlaces.instance.get_places_by_type(type)
    # end
    render json: { disabled: true }
  end

  def show
    business_data = Rails.cache.fetch(cache_key(params[:type]), expires_in: 1.week) do |key|
      Clients::GooglePlaces.instance.get_places_by_type(type)
    end
    @places = business_data[:results].map { |place| Map::Place.new(place) }
    @places = Map::Place.sanitize_list!(@places)
  end

  def experience
    @options = PLACES_CONFIG["tags"]
  end

  private

    def cache_key(type)
      "google_api:places_nearby:type:#{type}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def map_link(place)
    coordinates = place.coordinates
    name = URI.encode_www_form_component(place.name)
    if browser.platform.ios?
      "maps://?q=#{name}&ll=#{coordinates.latitude},#{coordinates.longitude}"
    else
      "https://www.google.com/maps/place/?q=place_id:#{place.google_place_id}"
    end
  end
end

app/helpers/cache_helper.rb
module CacheHelper
end

app/helpers/experience_helper.rb
module ExperienceHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_area_helper.rb
module TestAreaHelper
end

app/views/experience/index.html.erb
<div>
  <div class="my-4">
    <h1>Welcome to Downtown Ventura!</h1>
    <p class="text-lg not-bold italic mx-2 text-gray-400">Let's find something to do!</h1>
  </div>
  <div class="px-5">
    <% @options.each do |key, option| %>
      <%= link_to experience_path(key) do %>
        <div class="cursor-pointer bg-white p-4 rounded-lg shadow-md mb-2">
          <h2><%= option["prompt"]%> <span>➡️</span></h2>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/experience/show.html.erb
<div><%= link_to "Back", experiences_path %></div>
<% @places.each_with_index do |place, idx| %>
  <% index = idx + 1%>
  <div
    class="bg-white shadow-md rounded-lg p-4 my-3"
    data-controller="place"
    data-place-data-value="<%= {place: place, index: index }.to_json %>"
    data-map-target="place"
  >
    <div class="flex items-center justify-between">
      <!-- Index Number -->
      <div class="w-10 h-10 flex items-center justify-center bg-blue-500 text-white rounded-full">
        <%= index %>
      </div>
      <!-- Place Name and Distance -->
      <div class="flex-1 mx-4">
        <h2 class="text-lg font-semibold"><%= place.name %></h2>
        <p class="text-gray-400" data-place-target="distance"></p>
      </div>
      <!-- Google Maps Link -->
      <a
            href="<%= map_link(place) %>"
            target="_blank"
            class="flex items-center justify-center w-10 h-10 bg-green-500 text-white rounded-full hover:bg-green-600 transition-colors"
          >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a2 2 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      </a>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div>
  <div class="px-5">
    <% @places_by_type.each do |type, places| %>
      <div>
        <h1><%= type.to_s.humanize %></h1>
        <% places.map do |place| %>
          <div class="mx-4 my-2 text-gray-600">
            <%= link_to place.name, map_link(place) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Msm Map" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <!-- Leaflet JS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"/></script>
    <script>
      window.isLocalDevelopment = <%= Rails.application.config.force_mock_location || false %>;
    </script>
  </head>
  <body>
    <main class="container mx-auto">
      <div data-controller="map">
        <div class="bg-blue-500 text-white p-4">
          Main Street Moves Directory (WIP)
        </div>
        <div id="map" style="height: 200px;"></div>
        <div class="px-3">
          <%= yield %>
        </div>
      </main>
    </body>
  </html>

app/views/test_area/experience.html.erb
<div>
  <div class="my-4">
    <h1>Welcome to Downtown Ventura!</h1>
    <p class="text-lg not-bold italic mx-2 text-gray-400">Let's find something to do!</h1>
  </div>
  <div class="px-5">
    <% @options.each do |key, option| %>
      <div class="cursor-pointer bg-white p-4 rounded-lg shadow-md mb-2">
        <h2><%= option["prompt"] %> <span>→</span></h2>
      </div>
    <% end %>
  </div> 
</div>

app/views/test_area/show.html.erb
<pre>
  <% @places.each do |place| %>
    <%= place.name%> (<%= place.coordinates.latitude %>, <%= place.coordinates.longitude %>, <%= place.google_place_id %>)
  <% end %>
</pre>